/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package org.nfunk.jep;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 7;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 8;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 9;
  /** RegularExpression Id. */
  int EXPONENT = 10;
  /** RegularExpression Id. */
  int STRING_LITERAL = 11;
  /** RegularExpression Id. */
  int INDENTIFIER1 = 12;
  /** RegularExpression Id. */
  int IDTYPE1 = 13;
  /** RegularExpression Id. */
  int LETTER1 = 14;
  /** RegularExpression Id. */
  int DIGIT1 = 15;
  /** RegularExpression Id. */
  int INDENTIFIER2 = 16;
  /** RegularExpression Id. */
  int IDTYPE2 = 17;
  /** RegularExpression Id. */
  int LETTER2 = 18;
  /** RegularExpression Id. */
  int DIGIT2 = 19;
  /** RegularExpression Id. */
  int ASSIGN = 20;
  /** RegularExpression Id. */
  int SEMI = 21;
  /** RegularExpression Id. */
  int COMMA = 22;
  /** RegularExpression Id. */
  int GT = 23;
  /** RegularExpression Id. */
  int LT = 24;
  /** RegularExpression Id. */
  int EQ = 25;
  /** RegularExpression Id. */
  int LE = 26;
  /** RegularExpression Id. */
  int GE = 27;
  /** RegularExpression Id. */
  int NE = 28;
  /** RegularExpression Id. */
  int AND = 29;
  /** RegularExpression Id. */
  int OR = 30;
  /** RegularExpression Id. */
  int PLUS = 31;
  /** RegularExpression Id. */
  int MINUS = 32;
  /** RegularExpression Id. */
  int MUL = 33;
  /** RegularExpression Id. */
  int DOT = 34;
  /** RegularExpression Id. */
  int DIV = 35;
  /** RegularExpression Id. */
  int MOD = 36;
  /** RegularExpression Id. */
  int NOT = 37;
  /** RegularExpression Id. */
  int POWER = 38;
  /** RegularExpression Id. */
  int CROSS = 39;
  /** RegularExpression Id. */
  int LSQ = 40;
  /** RegularExpression Id. */
  int RSQ = 41;
  /** RegularExpression Id. */
  int LRND = 42;
  /** RegularExpression Id. */
  int RRND = 43;
  /** RegularExpression Id. */
  int COLON = 44;

  /** Lexical state. */
  int NO_DOT_IN_IDENTIFIERS = 0;
  /** Lexical state. */
  int DEFAULT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<INDENTIFIER1>",
    "<IDTYPE1>",
    "<LETTER1>",
    "<DIGIT1>",
    "<INDENTIFIER2>",
    "<IDTYPE2>",
    "<LETTER2>",
    "<DIGIT2>",
    "\"=\"",
    "\";\"",
    "\",\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\".\"",
    "\"/\"",
    "\"%\"",
    "\"!\"",
    "\"^\"",
    "\"^^\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\":\"",
  };

}
